name: Makefile CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print working directory
      run: pwd

    - name: List directory contents
      run: ls -la

    - name: List directory contents of subfolders
      run: find .

    - name: Install dependencies
      run: make setup_tc

    - name: Run check
      run: make release_tc
